# Generated by Django 6.0.6 on 2026-06-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='pin_autorizacion',
            field=models.CharField(blank=True, help_text='Pin numerico de 6 digitos para autorizacion de transacciones', max_length=6, null=True),
        ),
    ]
